version: 2

run:
  timeout: 10m
  tests: true
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    # Core
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Security
    - gosec
    
    # Code quality
    - gocritic
    - gocyclo
    - dupl
    - misspell
    - dogsled
    - makezero
    - prealloc
    
    # Testing
    - paralleltest
    - testifylint
    
    # Modern practices
    - exhaustive
    - forbidigo

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 8
  gosec:
    excludes:
      - G204  # Subprocess launching may be allowed in this context
  dupl:
    threshold: 80
  misspell:
    locale: US
  forbidigo:
    forbid:
      - 'fmt\.Print.*'  # Use structured logging instead
    exclude-glob:
      - 'cmd/vikunja-cli/**/*.go'  # CLI tools need user output
      - 'pkg/vikunja/formatter.go' # Output formatting library
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = errors for explicit ignoring
    exclude-functions:
      - (fmt\.Fprintf).*outputWriter  # CLI user output is legitimate
    
  paralleltest:
    ignore-auto: false  # Require explicit t.Parallel() calls
