version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - gocyclo
    - funlen
    - gocheckcompilerdirectives
    - gocognit
    - godoclint
    - misspell
    - dogsled
    - makezero
    - prealloc
    - revive
    - testifylint
    - exhaustive
    - forbidigo
  settings:
    gocyclo:
      min-complexity: 8
    gosec:
      excludes:
        - G204
    gocognit:
      min-complexity: 20
    dupl:
      threshold: 80
    misspell:
      locale: US
    forbidigo:
      forbid:
        - pattern: "context.Background"
          msg: "Pass a context in or use t.Context()"
        - pattern: "context.TODO"
          msg: "Pass a context in or use t.Context()"
    godoclint:
      options:
        rules:
          - require-doc
          - start-with-name
          - max-len
    funlen:
      lines: 150
      statements: 100
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (fmt\.Fprintf).*outputWriter

formatters:
  enable:
    - gofmt
    - goimports
